# This file is machine-generated - editing it directly is not advised

julia_version = "1.8.2"
manifest_format = "2.0"
project_hash = "d12fea890bdac1c40eed40d3a63abc13d349e599"

[[deps.RemoteTestPkg]]
git-tree-sha1 = "b93e22bbda032622033744c458e0832293a07703"
repo-rev = "main"
repo-url = "https://github.com/white-alistair/RemoteTestPkg.jl.git"
uuid = "1c96aa74-8ecf-4a24-be7b-6c362101acb6"
version = "0.1.0"
